apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{.Values.grafana.ingress.host}}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{.Values.grafana.name}}-service
                port:
                  number: 3000
