apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.mimir.volume.config.configMap}}
  labels:
    app: {{.Values.mimir.name}}
data:
  mimir.yaml: |
    multitenancy_enabled: false

    blocks_storage:
    backend: filesystem
    bucket_store:
        sync_dir: /tmp/mimir/tsdb-sync
    filesystem:
        dir: /tmp/mimir/data/tsdb
    tsdb:
        dir: /tmp/mimir/tsdb

    server:
      http_listen_port: 9009
      log_level: info

    compactor:
      data_dir: /tmp/mimir/compactor
      sharding_ring:
        kvstore:
          store: memberlist

    distributor:
      ring:
        # The address advertised in the ring. Localhost.
        instance_addr: 127.0.0.1
        # Use memberlist backend store (the default).
        kvstore:
          store: memberlist

    ingester:
      ring:
        # The address advertised in the ring. Localhost.
        instance_addr: 127.0.0.1
        # Use memberlist backend store (the default).
        kvstore:
          store: memberlist
        # Note: It is highly recommended to run more than one ingester in production, the default is an RF of 3.
        replication_factor: 1

    ruler_storage:
      backend: filesystem
      filesystem:
        # The directory in which to store rules.
        dir: /tmp/mimir/rules

    store_gateway:
      sharding_ring:
        # Only run a single instance. In production setups, the replication factor must
        # be set on the querier and ruler as well.
        replication_factor: 1

    limits:
      max_global_exemplars_per_user: 100000
      ingestion_rate: 30000
