apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secret_name}}
type: Opaque
data:
  db_user: {{ .Values.secrets.db_user | b64enc | quote }}
  db_password: {{ .Values.secrets.db_password | b64enc | quote }}