tls:
  cert_manager:
    issuer: letsencrypt-issuer

alloy:
  name: alloy
  kind: Deployment
  specs:
    replicas: 1
    container_name: alloy
    image: grafana/alloy:v1.7.5
    ports:
      - port: 4317
        protocol: TCP
        exposed_port: 4317
        name: grpc
      - port: 12345
        protocol: TCP
        exposed_port: 12345
        name: self
      - port: 4318
        protocol: TCP
        exposed_port: 4318
        name: http
      - port: 9999
        protocol: TCP
        exposed_port: 9999
        name: pyroscope
  volume:
    config:
      name: alloy-config
      configMap: alloy-config
      path: /etc/config.alloy
      subPath: config.alloy
  ingress:
    http:
      hosts:
        - host: otel-http.neryolab.com
          path: /
          service_name: alloy-service
          pathType: Prefix
          tls_secret_name: alloy-http-tls
          port: 4318
        - host: alloy.neryolab.com
          path: /-/ready
          pathType: Exact
          service_name: alloy-service
          tls_secret_name: alloy-self-tls
          port: 12345
        - host: pyroscope.neryolab.com
          path: /
          service_name: alloy-service
          pathType: Prefix
          tls_secret_name: alloy-pyroscope-tls
          port: 9999
    grpc:
      hosts:
        - host: otel-grpc.neryolab.com
          path: /
          service_name: alloy-service
          tls_secret_name: alloy-grpc-tls
          port: 4317
  resources:
    limits:
      cpu: "500m"
      memory: "200Mi"
    requests:
      cpu: "250m"
      memory: "80Mi"
  hpa:
    min: 2
    max: 4
    cpu: 120
    memory: 120