tls:
  cert_manager:
    issuer: letsencrypt-issuer

postgres:
  name: pgsql
  kind: StatefulSet
  specs:
    replicas: 1
    image: postgres:16.8
    container_name: pgsql
    container_port: 5432
    exposed_port: 5432
    resources:
      limits:
        cpu: "400m"
        memory: "800Mi"
      requests:
        cpu: "50m"
        memory: "80Mi"
    secretEnv:
      - name: POSTGRES_USER
        secret_name: pg-secrets
        key: db_user
      - name: POSTGRES_PASSWORD
        secret_name: pg-secrets
        key: db_password
pvc:
  name: pgsql
  storage: 5Gi

secret_name: pg-secrets