apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secret_name}}
type: Opaque
data:
  db_dialect: {{ .Values.secrets.db_dialect | b64enc | quote }}
  db_host: {{ .Values.secrets.db_host | b64enc | quote }}
  db_port: {{ .Values.secrets.db_port | b64enc | quote }}
  db_name: {{ .Values.secrets.db_name | b64enc | quote }}
  db_user: {{ .Values.secrets.db_user | b64enc | quote }}
  db_password: {{ .Values.secrets.db_password | b64enc | quote }}
  admin_name: {{ .Values.secrets.admin_name | b64enc | quote }}
  admin_email: {{ .Values.secrets.admin_email | b64enc | quote }}
  admin_password: {{ .Values.secrets.admin_password | b64enc | quote }}