apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.semaphore.name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.semaphore.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.semaphore.specs.exposed_port }}
      targetPort: {{ .Values.semaphore.specs.container_port }}
