services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "5671:5671"
      - "15672:15672"
      # Port MQTT
      - "1883:1883"
      # Port MQTT with TLS/SSL
      - "8883:8883"
      # Port STOMP
      - "61613:61613"
      # Port STOMP with TLS/SSL
      - "61614:61614"
      # Port AMQP 1.0
      - "5673:5673"
      # Port stream protocol
      - "5552:5552"
      # Prometheus metrics
      - "15692:15692"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
    driver: local