{{- if eq .Values.amqps.kind "nodeport" }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-nodeport
  labels:
    app: {{.Values.name}}
spec:
  type: NodePort
  selector:
    app: {{.Values.name}}
  ports:
    - port: 5672
      targetPort: 5672
      nodePort: 30072
      name: amqp
    - port: 5671
      targetPort: 5671
      nodePort: 30073
      name: amqps
{{- end }}