apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
type: Opaque
data:
  default_user: {{.Values.secrets.default_user | b64enc | quote }}
  default_password: {{.Values.secrets.default_password | b64enc | quote }}
