apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  serviceName: {{ .Values.name }}-headless
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.specs.image }}
          ports: {{- range .Values.specs.ports }}
            - containerPort: {{ .port }}
          {{- end }}
          env:
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Values.name}}-secret
                  key: default_user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{.Values.name}}-secret
                  key: default_password
          volumeMounts:
            - name: config
              mountPath: /etc/rabbitmq
            - name: data
              mountPath: /var/lib/rabbitmq/mnesia
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name }}-configmap
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
