apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alloy.volume.config.configMap }}
  labels:
    app: {{ .Values.alloy.name }}
data:
  config.alloy: |
    {{- .Files.Get "config.alloy" | nindent 4 }}