apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alloy.volume.config.configMap }}
  labels:
    app: {{ .Values.alloy.name }}
data:
  {{- $files := .Files }}
  {{- range tuple "config.alloy" }}
  {{ . }}: |-
    {{ $files.Get . }}    
  {{- end }}