apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.alloy.name }}-grpc-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: {{ .Values.tls.cert_manager.issuer }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    {{- range .Values.alloy.ingress.grpc.hosts }}
    - hosts:
        - {{ .host }}
      secretName: {{ .tls_secret_name }}
    {{- end }}
  rules: {{- range .Values.alloy.ingress.grpc.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: {{ .path }}
            backend:
              service:
                name: {{ .service_name }}
                port:
                  number: {{ .port }}
  {{- end }}
