apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana_cloud.secret.name }}
type: Opaque
data:
  gc_endpoint: {{ .Values.grafana_cloud.secret.endpoint }}
  gc_username: {{ .Values.grafana_cloud.secret.username }}
  gc_password: {{ .Values.grafana_cloud.secret.password }}
  pyroscope_endpoint: {{ .Values.grafana_cloud.secret.pyroscope_endpoint }}
