apiVersion: apps/v1
kind: {{.Values.grafana.kind}}
metadata:
  name: {{.Values.grafana.name}}
  labels:
    app: {{.Values.grafana.name}}
spec:
  replicas: {{.Values.grafana.replicas}}
  selector:
    matchLabels:
      app: {{.Values.grafana.name}}
  template:
    metadata:
      labels:
        app: {{.Values.grafana.name}}
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: {{.Values.grafana.specs.container_name}}
          image: {{.Values.grafana.specs.image}}
          ports:
            - containerPort: {{.Values.grafana.specs.container_port}}
          env:
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Mi
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: flameGraph traceqlSearch correlations traceQLStreaming metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
            - name: GF_INSTALL_PLUGINS
              value: grafana-lokiexplore-app,grafana-exploretraces-app,grafana-pyroscope-app
          resources:
            limits:
              cpu: "500m"
              memory: "350Mi"
            requests:
              cpu: "120m"
              memory: "120Mi"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
                path: /api/health
                port: 3000
          livenessProbe:
            httpGet:
                path: /api/health
                port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 10
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: {{.Values.grafana.name}}-pv
            - name: {{.Values.grafana_provisioning.volume.config.name}}
              mountPath: {{.Values.grafana_provisioning.volume.config.path}}
              subPath: {{.Values.grafana_provisioning.volume.config.subPath}}
      volumes:
        - name: {{.Values.grafana.name}}-pv
          persistentVolumeClaim:
            claimName: {{.Values.grafana.volume.name}}
        - name: {{.Values.grafana_provisioning.volume.config.name}}
          configMap:
            name: {{.Values.grafana_provisioning.volume.config.configMap}}
