apiVersion: apps/v1
kind: {{.Values.grafana.kind}}
metadata:
  name: {{.Values.grafana.name}}
  labels:
    app: {{.Values.grafana.name}}
spec:
  replicas: {{.Values.grafana.replicas}}
  selector:
    matchLabels:
      app: {{.Values.grafana.name}}
  template:
    metadata:
      labels:
        app: {{.Values.grafana.name}}
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: {{.Values.grafana.specs.container_name}}
          image: {{.Values.grafana.specs.image}}
          ports:
            - containerPort: {{.Values.grafana.specs.container_port}}
          env:
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Mi
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: flameGraph traceqlSearch correlations traceQLStreaming metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
            - name: GF_INSTALL_PLUGINS
              value: grafana-lokiexplore-app,grafana-exploretraces-app,grafana-pyroscope-app
            - name: GF_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{.Values.secret_name}}
                  key: GF_DATABASE_URL
          resources:
            limits:
              cpu: "800m"
              memory: "500Mi"
            requests:
              cpu: "160m"
              memory: "250Mi"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
                path: /api/health
                port: 3000
          livenessProbe:
            httpGet:
                path: /api/health
                port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 10
