tls:
  cert_manager:
    issuer: letsencrypt-issuer

grafana:
  name: grafana
  kind: Deployment
  specs:
    replicas: 1
    container_name: grafana
    image: grafana/grafana:latest
    container_port: 3000
    exposed_port: 3000
  volume:
    name: grafana-pvc
    storage: 1Gi
  ingress:
    host: grafana.neryolab.com
  hpa:
    min: 1
    max: 2
    cpu: 120
    memory: 120

grafana_provisioning:
  volume:
    config:
      name: grafana-provisioning-conf
      configMap: grafana-provisioning-config
      path: /etc/grafana/provisioning/datasources/datasources.yaml
      subPath: datasources.yaml


alloy: